version: '3'
services:
  todofront:
    depends_on:
      - todoback
    build: ./todo-app/front-end/
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    restart: always
  todoback:
    build: ./todo-app/back-end/
    restart: always
    ports:
      - 3001:3001
  todotests:
    build: ./todo-app/tests/
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront